"/usr/bin/ld",
"-m", "elf_i386",
"-dynamic-linker", "/lib/ld-linux.so.2",
"/usr/lib32/crt1.o",
"/usr/lib32/crti.o",
"/usr/local/lib32/bcc/gcc/32/crtbegin.o",
"-L/usr/loca/lib32/bcc/gcc/32",
"-L/usr/lib32",
"-L/lib32",
"-L/usr/x86_64-pc-linux-gnu/lib",
"-L/usr/lib",
"-lc",
"/usr/local/lib32/bcc/gcc/32/crtend.o",
"/usr/lib32/crtn.o",
"-o", "$3",
"$1",
"$2",
"/usr/local/lib32/bcc/xfloat.o",
