"/usr/bin/ld",
"-m", "elf_i386",
"-dynamic-linker", "/lib/ld-linux.so.2",
"/usr/lib/crt1.o",
"/usr/lib/crti.o",
"/usr/local/lib/bcc/gcc/32/crtbegin.o",
"-L/usr/local/lib/bcc/gcc/32",
"-L/usr/lib",
"-L/lib",
"-L/usr/x86_64-pc-linux-gnu/lib",
"-L/usr/lib",
"$2",
"-lc",
"/usr/local/lib/bcc/gcc/32/crtend.o",
"/usr/lib/crtn.o",
"-o", "$3",
"$1",
"/usr/local/lib/bcc/xfloat.o",
