void f1(void)  { int a, b, c; a = a % b;  a = a % b % c; }
void f2(void)  { int a, b, c; a = a & b;  a = a & b & c; }
void f3(void)  { int a, b, c; a = a * b;  a = a * b * c; }
void f4(void)  { int a, b, c; a = a + b;  a = a + b + c; }
void f5(void)  { int a, b, c; a = a - b;  a = a - b - c; }
void f6(void)  { int a, b, c; a = a / b;  a = a / b / c; }
void f7(void)  { int a, b, c; a = a && b; a = a && b && c; }
void f8(void)  { int a, b, c; a = a || b; a = a || b || c; }
void f9(void)  { int a, b, c; a = a <= b; a = a <= b <= c; }
void f10(void) { int a, b, c; a = a == b; a = a == b == c; }
void f11(void) { int a, b, c; a = a != b; a = a != b != c; }
void f12(void) { int a, b, c; a = a >= b; a = a >= b >= c; }
void f13(void) { int a, b, c; a = a >> b; a = a >> b >> c; }
void f14(void) { int a, b, c; a = a << b; a = a << b << c; }
void f15(void) { int a, b, c; a = a < b;  a = a < b < c; }
void f16(void) { int a, b, c; a = a > b;  a = a > b > c; }
void f17(void) { int a, b, c; a = a ^ b;  a = a ^ b ^ c; }
void f18(void) { int a, b, c; a = a | b;  a = a | b | c; }
