"/usr/local/bin/beluga",
"-U__GNUC__",
/* "-D__STRICT_ANSI__", */
"-D_POSIX_SOURCE",
"-D__i386__",
"-D__unix__",
"-D__linux__",
"-D__gnuc_va_list=va_list",
"$1",
"--include-system=/usr/local/lib/bcc/include",
"--include-system=/usr/local/lib/bcc/gcc/include",
"--include-system=/usr/local/include",
"--include-system=/usr/include",
"--target=x86-linux",
"-v",
"-o", "$3",
"$2",
