"/usr/bin/ld",
"-m", "elf_i386",
"-dynamic-linker", "/lib/ld-linux.so.2",
"/usr/lib/crt1.o",
"/usr/lib/crti.o",
"/usr/local/lib/bcc/gcc/crtbegin.o",
"-L/usr/local/lib/bcc/gcc",
"-L/usr/lib",
"-lc",
"/usr/local/lib/bcc/gcc/crtend.o",
"/usr/lib/crtn.o",
"-o", "$3",
"$1",
"$2",
"/usr/local/lib/bcc/xfloat.o",
